id = "conl"
name = "CONL"
version = "1.0.0"
schema_version = 1
authors = ["Conrad Irwin <conrad.irwin@gmail.com>"]
description = "Syntax highlighting and LSP for CONL"
repository = "https://github.com/ConradIrwin/zed-extension-conl"

[grammars.conl]
repository = "https://github.com/ConradIrwin/tree-sitter-conl"
commit = "32a79438641256e7290f154d0afeaf4d6b2d5b36"

[language_servers.conl-lsp]
name = "conl-lsp"
languages = ["CONL"]
