name = "CONL"
grammar = "conl"
path_suffixes = ["conl"]
line_comments = ["# "]

auto_indent_on_paste = false
auto_indent_using_last_non_empty_line = false
increase_indent_pattern = "^[^=]*=? *(#.*)?$"
prettier_parser_name = "yaml"
tab_size = 2
